hosts:
  - name: target-200-160-19-2
    ip: 200.160.19.2
    ssh_user: root
    environment: piloto
    criticality: alta
    openpanel: false
    internet_exposed: false
    access_path: "root@200.160.19.14 -> root@200.160.19.2"
