hosts:
  - name: radius
    ip: 192.168.1.30
    ssh_user: root
    environment: piloto
    criticality: alta
    openpanel: false
    internet_exposed: false
    access_path: "root@192.168.1.22 -> root@192.168.1.30"
